# Generated by Django 4.2.8 on 2024-01-30 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='book',
    #         name='title',
    #         field=models.CharField(default=django.utils.timezone.now, max_length=255),
    #         preserve_default=False,
    #     ),
    # ]
